# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Novatek NT36xxx touchscreen driver.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_NVT_D2S) += nt36xxx.o
obj-$(CONFIG_BOOT_FW_UPDATE_NVT_D2S) += nt36xxx_fw_update.o
