ccflags-y := -I$(src) -Wall -Werror

obj-y += elliptic.o
obj-y += elliptic_mixer_controls.o
obj-y += elliptic_data_msm_io.o
obj-y += elliptic_data_userspace_io.o
obj-y += elliptic_data_userspace_ctrl.o
obj-y += elliptic_sysfs.o
